using Shouldly;
using Solutions._2024;

namespace Solutions.UnitTest._2024;

[TestClass]
public class Day8Test
{
    [TestMethod]
    public void Part1Test1()
    {
        var day = new Day8();
        const string data = """
                            ............
                            ........0...
                            .....0......
                            .......0....
                            ....0.......
                            ......A.....
                            ............
                            ............
                            ........A...
                            .........A..
                            ............
                            ............
                            """;
        var result = day.Part1(data);
        result.ShouldBe(14);
    }

    [TestMethod]
    public void Part2Test1()
    {
        var day = new Day8();
        const string data = """
                            T.........
                            ...T......
                            .T........
                            ..........
                            ..........
                            ..........
                            ..........
                            ..........
                            ..........
                            ..........
                            """;
        var result = day.Part2(data);
        result.ShouldBe(9);
    }

    [TestMethod]
    public void Part2Test2()
    {
        var day = new Day8();
        const string data = """
                            ............
                            ........0...
                            .....0......
                            .......0....
                            ....0.......
                            ......A.....
                            ............
                            ............
                            ........A...
                            .........A..
                            ............
                            ............
                            """;
        var result = day.Part2(data);
        result.ShouldBe(34);
    }
}